package main.gui;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import main.event.Events;
import main.game.GameInfoPrinter;
import main.game.TowersOfHanoiGame;

import javax.swing.*;
import javax.swing.text.DefaultCaret;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 * Created by Dylan on 31/12/16.
 */
@Singleton
public class GameGui extends JFrame {
    private final TowersOfHanoiGame game;
    private final Events.OutputText outputTextEvent;

    private JPanel mainPanel;
    private JTextArea gameOut;
    private JTextField userInput;
    private JScrollPane gameOutScroll;

    @Inject
    public GameGui(TowersOfHanoiGame game,
                   Events.OutputText outputTextEvent) {
        this.game = game;
        this.outputTextEvent = outputTextEvent;
        configureGui();
        setupEvents();
    }

    private void configureGui() {
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setContentPane(mainPanel);

        Font font = new Font("monospaced", Font.PLAIN, 12);
        gameOut.setFont(font);
        userInput.setFont(font);

        gameOut.setColumns(GameInfoPrinter.WIDTH + 1);

        // Make gameOut scroll to the bottom automatically
        ((DefaultCaret) gameOut.getCaret())
                .setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        pack();
        setVisible(true);
        setResizable(false);
    }

    private void setupEvents() {
        userInput.addActionListener(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onUserEnteredLine();
            }
        });
        outputTextEvent.registerListener(str -> {
            gameOut.append(str);
        });
    }

    private void onUserEnteredLine() {
        game.onUserInputtedLine(userInput.getText());
        userInput.setText("");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        gameOutScroll = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(gameOutScroll, gbc);
        gameOut = new JTextArea();
        gameOut.setColumns(0);
        gameOut.setEditable(false);
        gameOut.setLineWrap(true);
        gameOut.setRows(20);
        gameOutScroll.setViewportView(gameOut);
        userInput = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(userInput, gbc);
        final JLabel label1 = new JLabel();
        label1.setText(">");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label1, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
